server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://accessosicuro-trial.rete.toscana.it/auth/realms/arpa/protocol/openid-connect/certs
  flyway:
    enabled: false

marvel:
  base-url: http://gateway.marvel.com/v1/public
#  api-key: abcd
#  api-secret: abcd



feign:
  okhttp:
    enabled: true
  compression:
    request:
      mime-types: application/json
    response:
      useGzipDecoder: true
      enabled: true